version: "3.9"
services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul
    command: consul agent -dev -ui -client=0.0.0.0
    ports:
      - "8500:8500"     # UI / API HTTP
      - "8600:8600/udp" # DNS
    networks:
      - consul-net



networks:
  consul-net:
    driver: bridge
