server:
  port: 0   # puerto aleatorio

spring:
  application:
    name: usuario-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        register: true
#       instance-host: ${HOSTNAME:localhost}  # opcional
management:
  endpoints.web.exposure.include: health,info
