spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usuariosdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
  profiles:
    active: dev1